### PR TITLE
Update Readme with new screenshots issue

### PR DESCRIPTION
**Pull request by yagmurerdogan**
- Screenshots are updated by using https://mockuphone.com/
- Contributing section added

### CODE REVIEW

**Comment by UbadahJ** [comment]
@yagmurerdogan The ReadMe looks good enough but the frame used seems to be clipping the status bar date. Wouldn't it be better to have solid bezels of a smartphone like Pixel 4? Other than that, looks good

**Comment by yagmurerdogan** [comment]
@UbadahJ You right I didn't realize that before. Next time I will use pixel 4, thanks for advice 🙏🏻

**Comment by yagmurerdogan** [comment]
I just updated images with using Pixel 4 @UbadahJ Can you check and merge if there is no any problem 😊

**Comment by UbadahJ** [comment]
Seems good enough

**Comment by UbadahJ** [comment]
Good work!

**Pull request merged**
